{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "vfps.fullname" . }}
  labels:
    {{- include "vfps.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  podSelector:
    matchLabels:
      {{- include "vfps.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  policyTypes:
    - Ingress
    - Egress
  {{- if .Values.networkPolicy.allowExternalEgress }}
  egress:
    - {}
  {{- else }}
  egress:
    {{- if .Values.networkPolicy.extraEgress }}
    {{- include "common.tplvalues.render" (dict "value" .Values.networkPolicy.extraEgress "context" $) | nindent 4 }}
    {{- else }}
    []
    {{- end }}
  {{- end }}
  ingress:
    # the http and grpc ports both serve the same pseudonymization API, so they share one rule
    - ports:
        - port: http
        - port: grpc
      from:
      {{- if not .Values.networkPolicy.allowExternal }}
        - podSelector:
            matchLabels:
              {{ include "vfps.fullname" . }}-client: "true"
      {{- end }}
      {{- if .Values.networkPolicy.ingressNSMatchLabels }}
        - namespaceSelector:
            matchLabels:
              {{- range $key, $value := .Values.networkPolicy.ingressNSMatchLabels }}
              {{ $key | quote }}: {{ $value | quote }}
              {{- end }}
          {{- if .Values.networkPolicy.ingressNSPodMatchLabels }}
          podSelector:
            matchLabels:
              {{- range $key, $value := .Values.networkPolicy.ingressNSPodMatchLabels }}
              {{ $key | quote }}: {{ $value | quote }}
              {{- end }}
          {{- end }}
      {{- end }}
    {{- if .Values.serviceMonitor.enabled }}
    - ports:
        - port: http-metrics
      from:
      {{- if not .Values.networkPolicy.metrics.allowExternal }}
        - podSelector:
            matchLabels:
              {{ include "vfps.fullname" . }}-client: "true"
      {{- end }}
      {{- if .Values.networkPolicy.metrics.ingressNSMatchLabels }}
        - namespaceSelector:
            matchLabels:
              {{- range $key, $value := .Values.networkPolicy.metrics.ingressNSMatchLabels }}
              {{ $key | quote }}: {{ $value | quote }}
              {{- end }}
          {{- if .Values.networkPolicy.metrics.ingressNSPodMatchLabels }}
          podSelector:
            matchLabels:
              {{- range $key, $value := .Values.networkPolicy.metrics.ingressNSPodMatchLabels }}
              {{ $key | quote }}: {{ $value | quote }}
              {{- end }}
          {{- end }}
      {{- end }}
    {{- end }}
    {{- if .Values.networkPolicy.extraIngress }}
    {{- include "common.tplvalues.render" (dict "value" .Values.networkPolicy.extraIngress "context" $) | nindent 4 }}
    {{- end }}
{{- end }}
