// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vfps.Data;

#nullable disable

namespace Vfps.Migrations
{
    [DbContext(typeof(PseudonymContext))]
    [Migration("20221207170557_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vfps.Data.Models.Namespace", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<int>("PseudonymGenerationMethod")
                        .HasColumnType("integer")
                        .HasColumnName("pseudonym_generation_method");

                    b.Property<long>("PseudonymLength")
                        .HasColumnType("bigint")
                        .HasColumnName("pseudonym_length");

                    b.Property<string>("PseudonymPrefix")
                        .HasColumnType("text")
                        .HasColumnName("pseudonym_prefix");

                    b.Property<string>("PseudonymSuffix")
                        .HasColumnType("text")
                        .HasColumnName("pseudonym_suffix");

                    b.HasKey("Name")
                        .HasName("pk_namespaces");

                    b.ToTable("namespaces", (string)null);
                });

            modelBuilder.Entity("Vfps.Data.Models.Pseudonym", b =>
                {
                    b.Property<string>("NamespaceName")
                        .HasColumnType("text")
                        .HasColumnName("namespace_name");

                    b.Property<string>("OriginalValue")
                        .HasColumnType("text")
                        .HasColumnName("original_value");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("PseudonymValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pseudonym_value");

                    b.HasKey("NamespaceName", "OriginalValue")
                        .HasName("pk_pseudonyms");

                    b.ToTable("pseudonyms", (string)null);
                });

            modelBuilder.Entity("Vfps.Data.Models.Pseudonym", b =>
                {
                    b.HasOne("Vfps.Data.Models.Namespace", null)
                        .WithMany("Pseudonyms")
                        .HasForeignKey("NamespaceName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pseudonyms_namespaces_namespace_name");
                });

            modelBuilder.Entity("Vfps.Data.Models.Namespace", b =>
                {
                    b.Navigation("Pseudonyms");
                });
#pragma warning restore 612, 618
        }
    }
}
