// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vfps.Data;

#nullable disable

namespace Vfps.Migrations
{
    [DbContext(typeof(PseudonymContext))]
    [Migration("20260910133817_ReplaceMetricSnapshotsWithPseudonymCounts")]
    partial class ReplaceMetricSnapshotsWithPseudonymCounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vfps.Data.Models.Namespace", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("AllowsMultiplePseudonyms")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_multiple_pseudonyms");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("OriginalValueValidationRegex")
                        .HasColumnType("text")
                        .HasColumnName("original_value_validation_regex");

                    b.Property<string>("ParentName")
                        .HasColumnType("text")
                        .HasColumnName("parent_name");

                    b.Property<int>("ParentValidationMode")
                        .HasColumnType("integer")
                        .HasColumnName("parent_validation_mode");

                    b.Property<int>("PseudonymGenerationMethod")
                        .HasColumnType("integer")
                        .HasColumnName("pseudonym_generation_method");

                    b.Property<long>("PseudonymLength")
                        .HasColumnType("bigint")
                        .HasColumnName("pseudonym_length");

                    b.Property<string>("PseudonymPrefix")
                        .HasColumnType("text")
                        .HasColumnName("pseudonym_prefix");

                    b.Property<string>("PseudonymSuffix")
                        .HasColumnType("text")
                        .HasColumnName("pseudonym_suffix");

                    b.HasKey("Name")
                        .HasName("pk_namespaces");

                    b.HasIndex("ParentName")
                        .HasDatabaseName("ix_namespaces_parent_name");

                    b.ToTable("namespaces", (string)null);
                });

            modelBuilder.Entity("Vfps.Data.Models.NamespaceAccessGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CanRead")
                        .HasColumnType("boolean")
                        .HasColumnName("can_read");

                    b.Property<bool>("CanReverseLookup")
                        .HasColumnType("boolean")
                        .HasColumnName("can_reverse_lookup");

                    b.Property<bool>("CanWrite")
                        .HasColumnType("boolean")
                        .HasColumnName("can_write");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Grantee")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grantee");

                    b.Property<int>("GranteeType")
                        .HasColumnType("integer")
                        .HasColumnName("grantee_type");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("NamespaceName")
                        .HasColumnType("text")
                        .HasColumnName("namespace_name");

                    b.HasKey("Id")
                        .HasName("pk_namespace_access_grants");

                    b.HasIndex("GranteeType", "Grantee")
                        .IsUnique()
                        .HasDatabaseName("ix_namespace_access_grants_global_grantee")
                        .HasFilter("namespace_name IS NULL");

                    b.HasIndex("NamespaceName", "GranteeType", "Grantee")
                        .IsUnique()
                        .HasDatabaseName("ix_namespace_access_grants_namespace_grantee")
                        .HasFilter("namespace_name IS NOT NULL");

                    b.ToTable("namespace_access_grants", (string)null);
                });

            modelBuilder.Entity("Vfps.Data.Models.Pseudonym", b =>
                {
                    b.Property<string>("NamespaceName")
                        .HasColumnType("text")
                        .HasColumnName("namespace_name");

                    b.Property<string>("OriginalValue")
                        .HasColumnType("text")
                        .HasColumnName("original_value");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("PseudonymValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pseudonym_value");

                    b.HasKey("NamespaceName", "OriginalValue", "SequenceNumber")
                        .HasName("pk_pseudonyms");

                    b.HasIndex("NamespaceName", "PseudonymValue")
                        .HasDatabaseName("ix_pseudonyms_namespace_name_pseudonym_value")
                        .HasAnnotation("Npgsql:CreatedConcurrently", true);

                    b.HasIndex("NamespaceName", "CreatedAt", "OriginalValue", "SequenceNumber")
                        .HasDatabaseName("ix_pseudonyms_namespace_name_created_at_original_value_sequence_number")
                        .HasAnnotation("Npgsql:CreatedConcurrently", true);

                    b.ToTable("pseudonyms", (string)null);
                });

            modelBuilder.Entity("Vfps.Data.Models.PseudonymCount", b =>
                {
                    b.Property<string>("NamespaceName")
                        .HasColumnType("text")
                        .HasColumnName("namespace_name");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<long>("Count")
                        .HasColumnType("bigint")
                        .HasColumnName("count");

                    b.HasKey("NamespaceName")
                        .HasName("pk_pseudonym_counts");

                    b.ToTable("pseudonym_counts", (string)null);
                });

            modelBuilder.Entity("Vfps.Data.Models.PseudonymizationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BadDataRowCount")
                        .HasColumnType("integer")
                        .HasColumnName("bad_data_row_count");

                    b.Property<long>("BytesProcessed")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes_processed");

                    b.Property<string>("ColumnMappings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("column_mappings");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Delimiter")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delimiter");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<string>("Encoding")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encoding");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("HangfireJobId")
                        .HasColumnType("text")
                        .HasColumnName("hangfire_job_id");

                    b.Property<bool>("HasHeaderRow")
                        .HasColumnType("boolean")
                        .HasColumnName("has_header_row");

                    b.Property<string>("InputObjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_object_key");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<int>("MissingValueCount")
                        .HasColumnType("integer")
                        .HasColumnName("missing_value_count");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("text")
                        .HasColumnName("original_file_name");

                    b.Property<string>("OutputObjectKey")
                        .HasColumnType("text")
                        .HasColumnName("output_object_key");

                    b.Property<long>("RowsProcessed")
                        .HasColumnType("bigint")
                        .HasColumnName("rows_processed");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("total_bytes");

                    b.HasKey("Id")
                        .HasName("pk_pseudonymization_jobs");

                    b.ToTable("pseudonymization_jobs", (string)null);
                });

            modelBuilder.Entity("Vfps.Data.Models.Namespace", b =>
                {
                    b.HasOne("Vfps.Data.Models.Namespace", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_namespaces_namespaces_parent_name");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Vfps.Data.Models.NamespaceAccessGrant", b =>
                {
                    b.HasOne("Vfps.Data.Models.Namespace", "Namespace")
                        .WithMany("AccessGrants")
                        .HasForeignKey("NamespaceName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_namespace_access_grants_namespaces_namespace_name");

                    b.Navigation("Namespace");
                });

            modelBuilder.Entity("Vfps.Data.Models.Pseudonym", b =>
                {
                    b.HasOne("Vfps.Data.Models.Namespace", null)
                        .WithMany("Pseudonyms")
                        .HasForeignKey("NamespaceName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pseudonyms_namespaces_namespace_name");
                });

            modelBuilder.Entity("Vfps.Data.Models.PseudonymCount", b =>
                {
                    b.HasOne("Vfps.Data.Models.Namespace", null)
                        .WithMany()
                        .HasForeignKey("NamespaceName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pseudonym_counts_namespaces_namespace_name");
                });

            modelBuilder.Entity("Vfps.Data.Models.Namespace", b =>
                {
                    b.Navigation("AccessGrants");

                    b.Navigation("Children");

                    b.Navigation("Pseudonyms");
                });
#pragma warning restore 612, 618
        }
    }
}
