postgres:
  auth:
    postgresPassword: "postgres"
    database: "vfps"

replicaCount: 3

serviceMonitor:
  enabled: false

resources:
  limits:
    memory: 256Mi
  requests:
    memory: 256Mi

database:
  additionalConnectionStringParameters: "Timeout=60;Max Auto Prepare=5;Maximum Pool Size=50;"

service:
  ui:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
      traefik.ingress.kubernetes.io/service.sticky.cookie.name: vfps-affinity

ingress:
  enabled: true
  hosts:
    - host: vfps.127.0.0.1.nip.io
      paths:
        - path: /v1
          pathType: Prefix
        - path: /
          pathType: Prefix
          serviceName: '{{ include "vfps.fullname" . }}-ui'

appsettings: |
  {
    "Init": {
      "v1": {
        "Namespaces": [
          {
            "Name": "default",
            "Description": "a default namespace created as part of the application startup",
            "PseudonymGenerationMethod": "SecureRandomBase64UrlEncoded",
            "PseudonymLength": 32,
            "PseudonymPrefix": "default-"
          }
        ]
      }
    }
  }
