name: benchmarks

on:
  push:
    tags:
      - "v*"
    branches: [master]
    paths:
      - src/**
  pull_request:
    branches: [master]
    paths:
      - src/**

permissions:
  contents: read

jobs:
  benchmark:
    runs-on: ubuntu-24.04
    name: benchmark
    permissions:
      contents: write
      pages: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install .NET
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          dotnet-version: "9.0.x"

      - name: Run benchmark
        run: dotnet run -c Release --project=src/Vfps.Benchmarks

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@a60cea5bc7b49e15c1f58f411161f99e0df48372 # v1.22.0
        with:
          name: PseudonymGeneratorBenchmarks
          tool: "benchmarkdotnet"
          output-file-path: BenchmarkDotNet.Artifacts/results/Vfps.Benchmarks.PseudonymGeneratorBenchmarks-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{github.event_name != 'pull_request'}}
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: "200%"
          comment-on-alert: true
          fail-on-alert: true
